### ISSUE TITLE
Finish!

### ISSUE THREAD

**Issue by pengsongyou** [pengsongyou/Sensors_Lab_Git#2]
Hey Armine,

In the morning, I spent 5 minutes asking Olivier questions and solve them all.
1. About the sin function, maybe you think too much :), just check the report.
2. About the image represent 3 parameters, we should put 3 parameters in H, S, V respectively, and then convert them to RGB images, that's all!
3. About the the image: angle of polarization, we should use 'imagesc' instead of 'imshow', because the range of the parameter is from -90 to 90.

That's it. Besides, I corrected a little your format mistakes. 
Please check again the report and then just send it to our teacher~ Thanks!

Cheers

**Comment by Armine13** [comment]
It's brilliant!
